# Generated by Django 4.1.5 on 2023-07-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Brunch", "Brunch"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Wine and Cocktails", "Wine and Cocktails"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("Appetizers", "Appetizers"),
                            ("Soups/Salads", "Soups/Salads"),
                            ("Entrees", "Entrees"),
                            ("Desserts", "Desserts"),
                            ("Wine", "Wine"),
                            ("Cocktails", "Cocktails"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("price", models.FloatField()),
                ("current", models.IntegerField(default=1)),
            ],
            options={
                "unique_together": {("name", "category")},
            },
        ),
    ]
