# Generated by Django 4.1.5 on 2023-07-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcewens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("Appetizers", "Appetizers"),
                    ("Soups/Salads", "Soups/Salads"),
                    ("Entrees", "Entrees"),
                    ("Desserts", "Desserts"),
                    ("Wine", "Wine"),
                    ("Cocktails", "Cocktails"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
