# Generated by Django 4.1.5 on 2023-07-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcewens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Appetizer", "Appetizer"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                    ("Dessert", "Dessert"),
                    ("Wine", "Wine"),
                ],
                max_length=50,
            ),
        ),
    ]
