# Generated by Django 4.1.5 on 2023-07-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcewens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                    ("Brunch", "Brunch"),
                    ("Wine", "Wine"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="menuitem",
            unique_together={("name", "category")},
        ),
    ]
