# Generated by Django 4.1.5 on 2023-07-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcewens", "0002_alter_menuitem_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Appetizers", "Appetizers"),
                    ("Soups/Salads", "Soups/Salads"),
                    ("Entrees", "Entrees"),
                    ("Desserts", "Desserts"),
                    ("Wine", "Wine"),
                    ("Cocktails", "Cocktails"),
                ],
                max_length=50,
            ),
        ),
    ]
