# Generated by Django 4.1.5 on 2023-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcewens", "0003_alter_menuitem_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="current",
            field=models.IntegerField(
                choices=[("On menu", 1), ("Not on menu", 0)], default=1
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Appetizers", "Appetizers"),
                    ("Salads", "Salads"),
                    ("Entrees", "Entrees"),
                    ("Sandwiches", "Sandwiches"),
                    ("Desserts", "Desserts"),
                    ("Wine", "Wine"),
                    ("Cocktails", "Cocktails"),
                ],
                max_length=50,
            ),
        ),
    ]
