# Generated by Django 4.1.5 on 2023-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcewens", "0004_alter_menuitem_current_alter_menuitem_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="current",
            field=models.IntegerField(
                choices=[(1, "On menu"), (0, "Not on menu")], default=1
            ),
        ),
    ]
