# Generated by Django 4.1.5 on 2023-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcewens", "0005_alter_menuitem_current"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.CharField(max_length=50),
        ),
    ]
